spring:
  application:
    name: JenkinsCICDPipeline
  datasource:
    url: jdbc:postgresql://localhost:5432/jenkins
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always